<?xml version="1.0" encoding="utf-8"?>
<Database Name="David" Class="AggregationSettingsDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=REN-SQL2;Initial Catalog=David;Integrated Security=True" SettingsObjectName="AscensionAnalytics.My.MySettings" SettingsPropertyName="DavidConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.AggregationSettings" Member="AggregationSettings">
    <Type Name="AggregationSetting">
      <Column Name="AggregationSettingId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SettingsEffectiveDate" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Column Name="DataAnalystPersonId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CurrentPolicyYearId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PreviousPolicyYearId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Previous2PolicyYearId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Previous3PolicyYearId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>