<?xml version="1.0" encoding="utf-8"?>
<Database Name="David" Class="AmeribenNetworkFeesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=REN-SQL2;Initial Catalog=David;Integrated Security=True" SettingsObjectName="AscensionAnalytics.My.MySettings" SettingsPropertyName="DavidConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Ameriben_NetworkFees" Member="Ameriben_NetworkFees">
    <Type Name="Ameriben_NetworkFee">
      <Column Name="NetworkFeeId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PaidDate" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Column Name="schoolgroup_cd" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="PolicyYear" Type="System.String" DbType="Char(9) NOT NULL" CanBeNull="false" />
      <Column Name="Paid" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="Network" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>