<?xml version="1.0" encoding="utf-8"?>
<Database Name="David" Class="DatasourceMaxPaidDateDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=REN-SQL2;Initial Catalog=David;Integrated Security=True" SettingsObjectName="AscensionAnalytics.My.MySettings" SettingsPropertyName="DavidConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.DatasourceMaxPaidDate" Member="DatasourceMaxPaidDates">
    <Type Name="DatasourceMaxPaidDate">
      <Column Name="datasource" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MaxPaidDate" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
    </Type>
  </Table>
</Database>