'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.5456
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Data
Imports System.Data.Linq
Imports System.Data.Linq.Mapping
Imports System.Linq
Imports System.Linq.Expressions
Imports System.Reflection


<System.Data.Linq.Mapping.DatabaseAttribute(Name:="David")>  _
Partial Public Class DatasourceMaxPaidDateDataContext
	Inherits System.Data.Linq.DataContext
	
	Private Shared mappingSource As System.Data.Linq.Mapping.MappingSource = New AttributeMappingSource
	
  #Region "Extensibility Method Definitions"
  Partial Private Sub OnCreated()
  End Sub
  #End Region
	
	Public Sub New()
		MyBase.New(Global.AscensionAnalytics.My.MySettings.Default.DavidConnectionString, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public ReadOnly Property DatasourceMaxPaidDates() As System.Data.Linq.Table(Of DatasourceMaxPaidDate)
		Get
			Return Me.GetTable(Of DatasourceMaxPaidDate)
		End Get
	End Property
End Class

<Table(Name:="dbo.DatasourceMaxPaidDate")>  _
Partial Public Class DatasourceMaxPaidDate
	
	Private _datasource As String
	
	Private _MaxPaidDate As System.Nullable(Of Date)
	
	Public Sub New()
		MyBase.New
	End Sub
	
	<Column(Storage:="_datasource", DbType:="VarChar(50) NOT NULL", CanBeNull:=false)>  _
	Public Property datasource() As String
		Get
			Return Me._datasource
		End Get
		Set
			If (String.Equals(Me._datasource, value) = false) Then
				Me._datasource = value
			End If
		End Set
	End Property
	
	<Column(Storage:="_MaxPaidDate", DbType:="SmallDateTime")>  _
	Public Property MaxPaidDate() As System.Nullable(Of Date)
		Get
			Return Me._MaxPaidDate
		End Get
		Set
			If (Me._MaxPaidDate.Equals(value) = false) Then
				Me._MaxPaidDate = value
			End If
		End Set
	End Property
End Class
