'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.5456
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Data
Imports System.Data.Linq
Imports System.Data.Linq.Mapping
Imports System.Linq
Imports System.Linq.Expressions
Imports System.Reflection


<System.Data.Linq.Mapping.DatabaseAttribute(Name:="David")>  _
Partial Public Class HthBenefitMappingDataContext
	Inherits System.Data.Linq.DataContext
	
	Private Shared mappingSource As System.Data.Linq.Mapping.MappingSource = New AttributeMappingSource
	
  #Region "Extensibility Method Definitions"
  Partial Private Sub OnCreated()
  End Sub
  Partial Private Sub InsertHTH_BenefitMapping(instance As HTH_BenefitMapping)
    End Sub
  Partial Private Sub UpdateHTH_BenefitMapping(instance As HTH_BenefitMapping)
    End Sub
  Partial Private Sub DeleteHTH_BenefitMapping(instance As HTH_BenefitMapping)
    End Sub
  Partial Private Sub InsertHTH_BENEFITS(instance As HTH_BENEFITS)
    End Sub
  Partial Private Sub UpdateHTH_BENEFITS(instance As HTH_BENEFITS)
    End Sub
  Partial Private Sub DeleteHTH_BENEFITS(instance As HTH_BENEFITS)
    End Sub
  Partial Private Sub InsertHTH_POS(instance As HTH_POS)
    End Sub
  Partial Private Sub UpdateHTH_POS(instance As HTH_POS)
    End Sub
  Partial Private Sub DeleteHTH_POS(instance As HTH_POS)
    End Sub
  Partial Private Sub InsertHthMapping_AscensionBenefits(instance As HthMapping_AscensionBenefits)
    End Sub
  Partial Private Sub UpdateHthMapping_AscensionBenefits(instance As HthMapping_AscensionBenefits)
    End Sub
  Partial Private Sub DeleteHthMapping_AscensionBenefits(instance As HthMapping_AscensionBenefits)
    End Sub
  #End Region
	
	Public Sub New()
		MyBase.New(Global.AscensionAnalytics.My.MySettings.Default.DavidConnectionString, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public ReadOnly Property HTH_BenefitMappings() As System.Data.Linq.Table(Of HTH_BenefitMapping)
		Get
			Return Me.GetTable(Of HTH_BenefitMapping)
		End Get
	End Property
	
	Public ReadOnly Property HTH_BENEFITS() As System.Data.Linq.Table(Of HTH_BENEFITS)
		Get
			Return Me.GetTable(Of HTH_BENEFITS)
		End Get
	End Property
	
	Public ReadOnly Property HTH_POS() As System.Data.Linq.Table(Of HTH_POS)
		Get
			Return Me.GetTable(Of HTH_POS)
		End Get
	End Property
	
	Public ReadOnly Property HthMapping_AscensionBenefits() As System.Data.Linq.Table(Of HthMapping_AscensionBenefits)
		Get
			Return Me.GetTable(Of HthMapping_AscensionBenefits)
		End Get
	End Property
End Class

<Table(Name:="dbo.HTH_BenefitMapping")>  _
Partial Public Class HTH_BenefitMapping
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _HTHBenefitMappingId As Integer
	
	Private _HTH_Benefit_Code As Integer
	
	Private _HTH_Place_Of_Service_Code As Integer
	
	Private _AscensionBenefitId As Integer
	
	Private _HTH_BENEFITS As EntityRef(Of HTH_BENEFITS)
	
	Private _HTH_POS As EntityRef(Of HTH_POS)
	
	Private _HthMappingBenefits As EntityRef(Of HthMapping_AscensionBenefits)
	
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnHTHBenefitMappingIdChanging(value As Integer)
    End Sub
    Partial Private Sub OnHTHBenefitMappingIdChanged()
    End Sub
    Partial Private Sub OnHTH_Benefit_CodeChanging(value As Integer)
    End Sub
    Partial Private Sub OnHTH_Benefit_CodeChanged()
    End Sub
    Partial Private Sub OnHTH_Place_Of_Service_CodeChanging(value As Integer)
    End Sub
    Partial Private Sub OnHTH_Place_Of_Service_CodeChanged()
    End Sub
    Partial Private Sub OnAscensionBenefitIdChanging(value As Integer)
    End Sub
    Partial Private Sub OnAscensionBenefitIdChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		Me._HTH_BENEFITS = CType(Nothing, EntityRef(Of HTH_BENEFITS))
		Me._HTH_POS = CType(Nothing, EntityRef(Of HTH_POS))
		Me._HthMappingBenefits = CType(Nothing, EntityRef(Of HthMapping_AscensionBenefits))
		OnCreated
	End Sub
	
	<Column(Storage:="_HTHBenefitMappingId", AutoSync:=AutoSync.OnInsert, DbType:="Int NOT NULL IDENTITY", IsPrimaryKey:=true, IsDbGenerated:=true)>  _
	Public Property HTHBenefitMappingId() As Integer
		Get
			Return Me._HTHBenefitMappingId
		End Get
		Set
			If ((Me._HTHBenefitMappingId = value)  _
						= false) Then
				Me.OnHTHBenefitMappingIdChanging(value)
				Me.SendPropertyChanging
				Me._HTHBenefitMappingId = value
				Me.SendPropertyChanged("HTHBenefitMappingId")
				Me.OnHTHBenefitMappingIdChanged
			End If
		End Set
	End Property
	
	<Column(Storage:="_HTH_Benefit_Code", DbType:="Int NOT NULL")>  _
	Public Property HTH_Benefit_Code() As Integer
		Get
			Return Me._HTH_Benefit_Code
		End Get
		Set
			If ((Me._HTH_Benefit_Code = value)  _
						= false) Then
				If Me._HTH_BENEFITS.HasLoadedOrAssignedValue Then
					Throw New System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException
				End If
				Me.OnHTH_Benefit_CodeChanging(value)
				Me.SendPropertyChanging
				Me._HTH_Benefit_Code = value
				Me.SendPropertyChanged("HTH_Benefit_Code")
				Me.OnHTH_Benefit_CodeChanged
			End If
		End Set
	End Property
	
	<Column(Storage:="_HTH_Place_Of_Service_Code", DbType:="Int NOT NULL")>  _
	Public Property HTH_Place_Of_Service_Code() As Integer
		Get
			Return Me._HTH_Place_Of_Service_Code
		End Get
		Set
			If ((Me._HTH_Place_Of_Service_Code = value)  _
						= false) Then
				If Me._HTH_POS.HasLoadedOrAssignedValue Then
					Throw New System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException
				End If
				Me.OnHTH_Place_Of_Service_CodeChanging(value)
				Me.SendPropertyChanging
				Me._HTH_Place_Of_Service_Code = value
				Me.SendPropertyChanged("HTH_Place_Of_Service_Code")
				Me.OnHTH_Place_Of_Service_CodeChanged
			End If
		End Set
	End Property
	
	<Column(Storage:="_AscensionBenefitId", DbType:="Int NOT NULL")>  _
	Public Property AscensionBenefitId() As Integer
		Get
			Return Me._AscensionBenefitId
		End Get
		Set
			If ((Me._AscensionBenefitId = value)  _
						= false) Then
				If Me._HthMappingBenefits.HasLoadedOrAssignedValue Then
					Throw New System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException
				End If
				Me.OnAscensionBenefitIdChanging(value)
				Me.SendPropertyChanging
				Me._AscensionBenefitId = value
				Me.SendPropertyChanged("AscensionBenefitId")
				Me.OnAscensionBenefitIdChanged
			End If
		End Set
	End Property
	
	<Association(Name:="HTH_BENEFITS_HTH_BenefitMapping", Storage:="_HTH_BENEFITS", ThisKey:="HTH_Benefit_Code", OtherKey:="BENEFIT_CODE", IsForeignKey:=true)>  _
	Public Property HTH_BENEFITS() As HTH_BENEFITS
		Get
			Return Me._HTH_BENEFITS.Entity
		End Get
		Set
			Dim previousValue As HTH_BENEFITS = Me._HTH_BENEFITS.Entity
			If ((Object.Equals(previousValue, value) = false)  _
						OrElse (Me._HTH_BENEFITS.HasLoadedOrAssignedValue = false)) Then
				Me.SendPropertyChanging
				If ((previousValue Is Nothing)  _
							= false) Then
					Me._HTH_BENEFITS.Entity = Nothing
					previousValue.HTH_BenefitMappings.Remove(Me)
				End If
				Me._HTH_BENEFITS.Entity = value
				If ((value Is Nothing)  _
							= false) Then
					value.HTH_BenefitMappings.Add(Me)
					Me._HTH_Benefit_Code = value.BENEFIT_CODE
				Else
					Me._HTH_Benefit_Code = CType(Nothing, Integer)
				End If
				Me.SendPropertyChanged("HTH_BENEFITS")
			End If
		End Set
	End Property
	
	<Association(Name:="HTH_POS_HTH_BenefitMapping", Storage:="_HTH_POS", ThisKey:="HTH_Place_Of_Service_Code", OtherKey:="PLACE_OF_SERVICE_CODE", IsForeignKey:=true)>  _
	Public Property HTH_POS() As HTH_POS
		Get
			Return Me._HTH_POS.Entity
		End Get
		Set
			Dim previousValue As HTH_POS = Me._HTH_POS.Entity
			If ((Object.Equals(previousValue, value) = false)  _
						OrElse (Me._HTH_POS.HasLoadedOrAssignedValue = false)) Then
				Me.SendPropertyChanging
				If ((previousValue Is Nothing)  _
							= false) Then
					Me._HTH_POS.Entity = Nothing
					previousValue.HTH_BenefitMappings.Remove(Me)
				End If
				Me._HTH_POS.Entity = value
				If ((value Is Nothing)  _
							= false) Then
					value.HTH_BenefitMappings.Add(Me)
					Me._HTH_Place_Of_Service_Code = value.PLACE_OF_SERVICE_CODE
				Else
					Me._HTH_Place_Of_Service_Code = CType(Nothing, Integer)
				End If
				Me.SendPropertyChanged("HTH_POS")
			End If
		End Set
	End Property
	
	<Association(Name:="HthMapping_AscensionBenefits_HTH_BenefitMapping", Storage:="_HthMappingBenefits", ThisKey:="AscensionBenefitId", OtherKey:="BenefitId", IsForeignKey:=true)>  _
	Public Property HthMapping_AscensionBenefits() As HthMapping_AscensionBenefits
		Get
			Return Me._HthMappingBenefits.Entity
		End Get
		Set
			Dim previousValue As HthMapping_AscensionBenefits = Me._HthMappingBenefits.Entity
			If ((Object.Equals(previousValue, value) = false)  _
						OrElse (Me._HthMappingBenefits.HasLoadedOrAssignedValue = false)) Then
				Me.SendPropertyChanging
				If ((previousValue Is Nothing)  _
							= false) Then
					Me._HthMappingBenefits.Entity = Nothing
					previousValue.HTH_BenefitMappings.Remove(Me)
				End If
				Me._HthMappingBenefits.Entity = value
				If ((value Is Nothing)  _
							= false) Then
					value.HTH_BenefitMappings.Add(Me)
					Me._AscensionBenefitId = value.BenefitId
				Else
					Me._AscensionBenefitId = CType(Nothing, Integer)
				End If
				Me.SendPropertyChanged("HthMapping_AscensionBenefits")
			End If
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
End Class

<Table(Name:="dbo.HTH_BENEFITS")>  _
Partial Public Class HTH_BENEFITS
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _BENEFIT_CODE As Integer
	
	Private _BENEFIT_DESCRIPTION As String
	
	Private _HTH_BenefitMappings As EntitySet(Of HTH_BenefitMapping)
	
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnBENEFIT_CODEChanging(value As Integer)
    End Sub
    Partial Private Sub OnBENEFIT_CODEChanged()
    End Sub
    Partial Private Sub OnBENEFIT_DESCRIPTIONChanging(value As String)
    End Sub
    Partial Private Sub OnBENEFIT_DESCRIPTIONChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		Me._HTH_BenefitMappings = New EntitySet(Of HTH_BenefitMapping)(AddressOf Me.attach_HTH_BenefitMappings, AddressOf Me.detach_HTH_BenefitMappings)
		OnCreated
	End Sub
	
	<Column(Storage:="_BENEFIT_CODE", DbType:="Int NOT NULL", IsPrimaryKey:=true)>  _
	Public Property BENEFIT_CODE() As Integer
		Get
			Return Me._BENEFIT_CODE
		End Get
		Set
			If ((Me._BENEFIT_CODE = value)  _
						= false) Then
				Me.OnBENEFIT_CODEChanging(value)
				Me.SendPropertyChanging
				Me._BENEFIT_CODE = value
				Me.SendPropertyChanged("BENEFIT_CODE")
				Me.OnBENEFIT_CODEChanged
			End If
		End Set
	End Property
	
	<Column(Storage:="_BENEFIT_DESCRIPTION", DbType:="VarChar(50) NOT NULL", CanBeNull:=false)>  _
	Public Property BENEFIT_DESCRIPTION() As String
		Get
			Return Me._BENEFIT_DESCRIPTION
		End Get
		Set
			If (String.Equals(Me._BENEFIT_DESCRIPTION, value) = false) Then
				Me.OnBENEFIT_DESCRIPTIONChanging(value)
				Me.SendPropertyChanging
				Me._BENEFIT_DESCRIPTION = value
				Me.SendPropertyChanged("BENEFIT_DESCRIPTION")
				Me.OnBENEFIT_DESCRIPTIONChanged
			End If
		End Set
	End Property
	
	<Association(Name:="HTH_BENEFITS_HTH_BenefitMapping", Storage:="_HTH_BenefitMappings", ThisKey:="BENEFIT_CODE", OtherKey:="HTH_Benefit_Code")>  _
	Public Property HTH_BenefitMappings() As EntitySet(Of HTH_BenefitMapping)
		Get
			Return Me._HTH_BenefitMappings
		End Get
		Set
			Me._HTH_BenefitMappings.Assign(value)
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
	
	Private Sub attach_HTH_BenefitMappings(ByVal entity As HTH_BenefitMapping)
		Me.SendPropertyChanging
		entity.HTH_BENEFITS = Me
	End Sub
	
	Private Sub detach_HTH_BenefitMappings(ByVal entity As HTH_BenefitMapping)
		Me.SendPropertyChanging
		entity.HTH_BENEFITS = Nothing
	End Sub
End Class

<Table(Name:="dbo.HTH_POS")>  _
Partial Public Class HTH_POS
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _PLACE_OF_SERVICE_CODE As Integer
	
	Private _PLACE_OF_SERVICE_DESCRIPTION As String
	
	Private _HTH_BenefitMappings As EntitySet(Of HTH_BenefitMapping)
	
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnPLACE_OF_SERVICE_CODEChanging(value As Integer)
    End Sub
    Partial Private Sub OnPLACE_OF_SERVICE_CODEChanged()
    End Sub
    Partial Private Sub OnPLACE_OF_SERVICE_DESCRIPTIONChanging(value As String)
    End Sub
    Partial Private Sub OnPLACE_OF_SERVICE_DESCRIPTIONChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		Me._HTH_BenefitMappings = New EntitySet(Of HTH_BenefitMapping)(AddressOf Me.attach_HTH_BenefitMappings, AddressOf Me.detach_HTH_BenefitMappings)
		OnCreated
	End Sub
	
	<Column(Storage:="_PLACE_OF_SERVICE_CODE", DbType:="Int NOT NULL", IsPrimaryKey:=true)>  _
	Public Property PLACE_OF_SERVICE_CODE() As Integer
		Get
			Return Me._PLACE_OF_SERVICE_CODE
		End Get
		Set
			If ((Me._PLACE_OF_SERVICE_CODE = value)  _
						= false) Then
				Me.OnPLACE_OF_SERVICE_CODEChanging(value)
				Me.SendPropertyChanging
				Me._PLACE_OF_SERVICE_CODE = value
				Me.SendPropertyChanged("PLACE_OF_SERVICE_CODE")
				Me.OnPLACE_OF_SERVICE_CODEChanged
			End If
		End Set
	End Property
	
	<Column(Storage:="_PLACE_OF_SERVICE_DESCRIPTION", DbType:="VarChar(50)")>  _
	Public Property PLACE_OF_SERVICE_DESCRIPTION() As String
		Get
			Return Me._PLACE_OF_SERVICE_DESCRIPTION
		End Get
		Set
			If (String.Equals(Me._PLACE_OF_SERVICE_DESCRIPTION, value) = false) Then
				Me.OnPLACE_OF_SERVICE_DESCRIPTIONChanging(value)
				Me.SendPropertyChanging
				Me._PLACE_OF_SERVICE_DESCRIPTION = value
				Me.SendPropertyChanged("PLACE_OF_SERVICE_DESCRIPTION")
				Me.OnPLACE_OF_SERVICE_DESCRIPTIONChanged
			End If
		End Set
	End Property
	
	<Association(Name:="HTH_POS_HTH_BenefitMapping", Storage:="_HTH_BenefitMappings", ThisKey:="PLACE_OF_SERVICE_CODE", OtherKey:="HTH_Place_Of_Service_Code")>  _
	Public Property HTH_BenefitMappings() As EntitySet(Of HTH_BenefitMapping)
		Get
			Return Me._HTH_BenefitMappings
		End Get
		Set
			Me._HTH_BenefitMappings.Assign(value)
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
	
	Private Sub attach_HTH_BenefitMappings(ByVal entity As HTH_BenefitMapping)
		Me.SendPropertyChanging
		entity.HTH_POS = Me
	End Sub
	
	Private Sub detach_HTH_BenefitMappings(ByVal entity As HTH_BenefitMapping)
		Me.SendPropertyChanging
		entity.HTH_POS = Nothing
	End Sub
End Class

<Table(Name:="dbo.Benefits")>  _
Partial Public Class HthMapping_AscensionBenefits
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _BenefitId As Integer
	
	Private _BenefitCode As String
	
	Private _BenefitDescription As String
	
	Private _IsRxBenefit As Byte
	
	Private _IsMentalHealthBenefit As Byte
	
	Private _IsInpatientBenefit As Byte
	
	Private _IsOfficeVisitBenefit As Byte
	
	Private _IsEmergencyRoomBenefit As Byte
	
	Private _HTH_BenefitMappings As EntitySet(Of HTH_BenefitMapping)
	
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnBenefitIdChanging(value As Integer)
    End Sub
    Partial Private Sub OnBenefitIdChanged()
    End Sub
    Partial Private Sub OnBenefitCodeChanging(value As String)
    End Sub
    Partial Private Sub OnBenefitCodeChanged()
    End Sub
    Partial Private Sub OnBenefitDescriptionChanging(value As String)
    End Sub
    Partial Private Sub OnBenefitDescriptionChanged()
    End Sub
    Partial Private Sub OnIsRxBenefitChanging(value As Byte)
    End Sub
    Partial Private Sub OnIsRxBenefitChanged()
    End Sub
    Partial Private Sub OnIsMentalHealthBenefitChanging(value As Byte)
    End Sub
    Partial Private Sub OnIsMentalHealthBenefitChanged()
    End Sub
    Partial Private Sub OnIsInpatientBenefitChanging(value As Byte)
    End Sub
    Partial Private Sub OnIsInpatientBenefitChanged()
    End Sub
    Partial Private Sub OnIsOfficeVisitBenefitChanging(value As Byte)
    End Sub
    Partial Private Sub OnIsOfficeVisitBenefitChanged()
    End Sub
    Partial Private Sub OnIsEmergencyRoomBenefitChanging(value As Byte)
    End Sub
    Partial Private Sub OnIsEmergencyRoomBenefitChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		Me._HTH_BenefitMappings = New EntitySet(Of HTH_BenefitMapping)(AddressOf Me.attach_HTH_BenefitMappings, AddressOf Me.detach_HTH_BenefitMappings)
		OnCreated
	End Sub
	
	<Column(Storage:="_BenefitId", AutoSync:=AutoSync.OnInsert, DbType:="Int NOT NULL IDENTITY", IsPrimaryKey:=true, IsDbGenerated:=true)>  _
	Public Property BenefitId() As Integer
		Get
			Return Me._BenefitId
		End Get
		Set
			If ((Me._BenefitId = value)  _
						= false) Then
				Me.OnBenefitIdChanging(value)
				Me.SendPropertyChanging
				Me._BenefitId = value
				Me.SendPropertyChanged("BenefitId")
				Me.OnBenefitIdChanged
			End If
		End Set
	End Property
	
	<Column(Storage:="_BenefitCode", DbType:="VarChar(15) NOT NULL", CanBeNull:=false)>  _
	Public Property BenefitCode() As String
		Get
			Return Me._BenefitCode
		End Get
		Set
			If (String.Equals(Me._BenefitCode, value) = false) Then
				Me.OnBenefitCodeChanging(value)
				Me.SendPropertyChanging
				Me._BenefitCode = value
				Me.SendPropertyChanged("BenefitCode")
				Me.OnBenefitCodeChanged
			End If
		End Set
	End Property
	
	<Column(Storage:="_BenefitDescription", DbType:="VarChar(50) NOT NULL", CanBeNull:=false)>  _
	Public Property BenefitDescription() As String
		Get
			Return Me._BenefitDescription
		End Get
		Set
			If (String.Equals(Me._BenefitDescription, value) = false) Then
				Me.OnBenefitDescriptionChanging(value)
				Me.SendPropertyChanging
				Me._BenefitDescription = value
				Me.SendPropertyChanged("BenefitDescription")
				Me.OnBenefitDescriptionChanged
			End If
		End Set
	End Property
	
	<Column(Storage:="_IsRxBenefit", DbType:="TinyInt NOT NULL")>  _
	Public Property IsRxBenefit() As Byte
		Get
			Return Me._IsRxBenefit
		End Get
		Set
			If ((Me._IsRxBenefit = value)  _
						= false) Then
				Me.OnIsRxBenefitChanging(value)
				Me.SendPropertyChanging
				Me._IsRxBenefit = value
				Me.SendPropertyChanged("IsRxBenefit")
				Me.OnIsRxBenefitChanged
			End If
		End Set
	End Property
	
	<Column(Storage:="_IsMentalHealthBenefit", DbType:="TinyInt NOT NULL")>  _
	Public Property IsMentalHealthBenefit() As Byte
		Get
			Return Me._IsMentalHealthBenefit
		End Get
		Set
			If ((Me._IsMentalHealthBenefit = value)  _
						= false) Then
				Me.OnIsMentalHealthBenefitChanging(value)
				Me.SendPropertyChanging
				Me._IsMentalHealthBenefit = value
				Me.SendPropertyChanged("IsMentalHealthBenefit")
				Me.OnIsMentalHealthBenefitChanged
			End If
		End Set
	End Property
	
	<Column(Storage:="_IsInpatientBenefit", DbType:="TinyInt NOT NULL")>  _
	Public Property IsInpatientBenefit() As Byte
		Get
			Return Me._IsInpatientBenefit
		End Get
		Set
			If ((Me._IsInpatientBenefit = value)  _
						= false) Then
				Me.OnIsInpatientBenefitChanging(value)
				Me.SendPropertyChanging
				Me._IsInpatientBenefit = value
				Me.SendPropertyChanged("IsInpatientBenefit")
				Me.OnIsInpatientBenefitChanged
			End If
		End Set
	End Property
	
	<Column(Storage:="_IsOfficeVisitBenefit", DbType:="TinyInt NOT NULL")>  _
	Public Property IsOfficeVisitBenefit() As Byte
		Get
			Return Me._IsOfficeVisitBenefit
		End Get
		Set
			If ((Me._IsOfficeVisitBenefit = value)  _
						= false) Then
				Me.OnIsOfficeVisitBenefitChanging(value)
				Me.SendPropertyChanging
				Me._IsOfficeVisitBenefit = value
				Me.SendPropertyChanged("IsOfficeVisitBenefit")
				Me.OnIsOfficeVisitBenefitChanged
			End If
		End Set
	End Property
	
	<Column(Storage:="_IsEmergencyRoomBenefit", DbType:="TinyInt NOT NULL")>  _
	Public Property IsEmergencyRoomBenefit() As Byte
		Get
			Return Me._IsEmergencyRoomBenefit
		End Get
		Set
			If ((Me._IsEmergencyRoomBenefit = value)  _
						= false) Then
				Me.OnIsEmergencyRoomBenefitChanging(value)
				Me.SendPropertyChanging
				Me._IsEmergencyRoomBenefit = value
				Me.SendPropertyChanged("IsEmergencyRoomBenefit")
				Me.OnIsEmergencyRoomBenefitChanged
			End If
		End Set
	End Property
	
	<Association(Name:="HthMapping_AscensionBenefits_HTH_BenefitMapping", Storage:="_HTH_BenefitMappings", ThisKey:="BenefitId", OtherKey:="AscensionBenefitId")>  _
	Public Property HTH_BenefitMappings() As EntitySet(Of HTH_BenefitMapping)
		Get
			Return Me._HTH_BenefitMappings
		End Get
		Set
			Me._HTH_BenefitMappings.Assign(value)
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
	
	Private Sub attach_HTH_BenefitMappings(ByVal entity As HTH_BenefitMapping)
		Me.SendPropertyChanging
		entity.HthMapping_AscensionBenefits = Me
	End Sub
	
	Private Sub detach_HTH_BenefitMappings(ByVal entity As HTH_BenefitMapping)
		Me.SendPropertyChanging
		entity.HthMapping_AscensionBenefits = Nothing
	End Sub
End Class
