<?xml version="1.0" encoding="utf-8"?>
<Database Name="David" Class="SchoolgroupLogoDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=REN-SQL2;Initial Catalog=David;Integrated Security=True" SettingsObjectName="AscensionAnalytics.My.MySettings" SettingsPropertyName="DavidConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.schoolgroup_logo" Member="schoolgroup_logos">
    <Type Name="schoolgroup_logo">
      <Column Name="schoolgroup_logo_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="schoolgroup_cd" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="logo_image" Type="System.Byte[]" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
</Database>