<?xml version="1.0" encoding="utf-8"?>
<Database Name="David" Class="AmeribenBenefitMappingDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=REN-SQL2;Initial Catalog=David;Integrated Security=True" SettingsObjectName="AscensionAnalytics.My.MySettings" SettingsPropertyName="DavidConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Benefits" Member="AmeribenMapping_AscensionBenefits">
    <Type Name="AmeribenMapping_AscensionBenefits">
      <Column Name="BenefitId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="BenefitCode" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="BenefitDescription" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="IsRxBenefit" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="IsMentalHealthBenefit" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="IsInpatientBenefit" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="IsOfficeVisitBenefit" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="IsEmergencyRoomBenefit" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Association Name="AmeribenMapping_AscensionBenefits_Ameriben_BenefitMapping" Member="Ameriben_BenefitMappings" ThisKey="BenefitId" OtherKey="AscensionBenefitId" Type="Ameriben_BenefitMapping" />
    </Type>
  </Table>
  <Table Name="dbo.Ameriben_BenefitMapping" Member="Ameriben_BenefitMappings">
    <Type Name="Ameriben_BenefitMapping">
      <Column Name="AmeribenBenefitMappingId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="AmeribenPOS" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="AmeribenTOS" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="AscensionBenefitId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="AmeribenMapping_AscensionBenefits_Ameriben_BenefitMapping" Member="AmeribenMapping_AscensionBenefits" Storage="_Benefits" ThisKey="AscensionBenefitId" OtherKey="BenefitId" Type="AmeribenMapping_AscensionBenefits" IsForeignKey="true" />
      <Association Name="Ameriben_POS_Ameriben_BenefitMapping" Member="Ameriben_POS" ThisKey="AmeribenPOS" OtherKey="POSCode" Type="Ameriben_POS" IsForeignKey="true" />
      <Association Name="Ameriben_TOS_Ameriben_BenefitMapping" Member="Ameriben_TOS" ThisKey="AmeribenTOS" OtherKey="ChargeType" Type="Ameriben_TOS" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Ameriben_POS" Member="Ameriben_POS">
    <Type Name="Ameriben_POS">
      <Column Name="POSCode" Type="System.String" DbType="Char(2) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="POSDescription" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="RenaissancePOSDescription" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Ameriben_POS_Ameriben_BenefitMapping" Member="Ameriben_BenefitMappings" ThisKey="POSCode" OtherKey="AmeribenPOS" Type="Ameriben_BenefitMapping" />
    </Type>
  </Table>
  <Table Name="dbo.Ameriben_TOS" Member="Ameriben_TOS">
    <Type Name="Ameriben_TOS">
      <Column Name="ChargeType" Type="System.String" DbType="VarChar(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DetailChargeType" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SummaryChargeType" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="BenefitType" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Association Name="Ameriben_TOS_Ameriben_BenefitMapping" Member="Ameriben_BenefitMappings" ThisKey="ChargeType" OtherKey="AmeribenTOS" Type="Ameriben_BenefitMapping" />
    </Type>
  </Table>
</Database>