<?xml version="1.0" encoding="utf-8"?>
<Database Name="David" Class="ClaremontSchoolgroupMappingDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=REN-SQL2;Initial Catalog=David;Integrated Security=True" SettingsObjectName="AscensionAnalytics.My.MySettings" SettingsPropertyName="DavidConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.ClaremontPlanHistoryData_TagMapping" Member="ClaremontPlanHistoryData_TagMappings">
    <Type Name="ClaremontPlanHistoryData_TagMapping">
      <Column Name="ClaremontPlanHistoryDataTagMapId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TagType" Type="System.String" DbType="VarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="SchoolgroupCode" Type="System.String" DbType="VarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="Tag" Type="System.String" DbType="VarChar(50) NULL" CanBeNull="false" />
      <Column Name="CollegeDisplay" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>