<?xml version="1.0" encoding="utf-8"?>
<Database Name="David" Class="DistriubtionTiersDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=REN-SQL2;Initial Catalog=David;Integrated Security=True" SettingsObjectName="AscensionAnalytics.My.MySettings" SettingsPropertyName="DavidConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Distributions" Member="Distributions">
    <Type Name="Distribution">
      <Column Name="DistributionId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DistributionName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="DistributionDescription" Type="System.String" DbType="VarChar(1000) NOT NULL" CanBeNull="false" />
      <Association Name="Distribution_DistributionTier" Member="DistributionTiers" ThisKey="DistributionId" OtherKey="DistributionId" Type="DistributionTier" />
    </Type>
  </Table>
  <Table Name="dbo.DistributionTiers" Member="DistributionTiers">
    <Type Name="DistributionTier">
      <Column Name="DistributionTierId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DistributionId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TierFloor" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="TierCeiling" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="TierDisplay" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="sortOrder" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Association Name="Distribution_DistributionTier" Member="Distribution" ThisKey="DistributionId" OtherKey="DistributionId" Type="Distribution" IsForeignKey="true" />
    </Type>
  </Table>
</Database>