<?xml version="1.0" encoding="utf-8"?>
<Database Name="David" Class="MarketingDbDataInDavidDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=REN-SQL2;Initial Catalog=David;Integrated Security=True" SettingsObjectName="AscensionAnalytics.My.MySettings" SettingsPropertyName="DavidConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.MarketingDb_Schools" Member="MarketingDb_Schools">
    <Type Name="MarketingDb_School">
      <Column Name="school" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.MarketingDB_SchoolgroupMapping" Member="MarketingDB_SchoolgroupMappings">
    <Type Name="MarketingDB_SchoolgroupMapping">
      <Column Name="MarketingDbSchoolgroupMappingId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MarketingDbSchool" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="MarketingDbPlan" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="PremiumAdministratorGroupCode" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
    </Type>
  </Table>
</Database>