<?xml version="1.0" encoding="utf-8"?>
<Database Name="David" Class="PiaBenefitMappingDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=REN-SQL2;Initial Catalog=David;Integrated Security=True" SettingsObjectName="AscensionAnalytics.My.MySettings" SettingsPropertyName="DavidConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.PIA_BenefitMapping" Member="PIA_BenefitMappings">
    <Type Name="PIA_BenefitMapping">
      <Column Name="PIABenefitMappingId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PIABenefitCode" Type="System.String" DbType="VarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="AscensionBenefitId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="PIA_Benefits_PIA_BenefitMapping" Member="PIA_Benefits" ThisKey="PIABenefitCode" OtherKey="bencode" Type="PIA_Benefits" IsForeignKey="true" />
      <Association Name="PiaMapping_AscensionBenefits_PIA_BenefitMapping" Member="PiaMapping_AscensionBenefits" ThisKey="AscensionBenefitId" OtherKey="BenefitId" Type="PiaMapping_AscensionBenefits" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PIA_Benefits" Member="PIA_Benefits">
    <Type Name="PIA_Benefits">
      <Column Name="bencode" Type="System.String" DbType="varchar(25) NOT NULL" IsReadOnly="true" IsPrimaryKey="true" CanBeNull="false" UpdateCheck="Always" />
      <Column Name="bendescription" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="PIA_Benefits_PIA_BenefitMapping" Member="PIA_BenefitMappings" ThisKey="bencode" OtherKey="PIABenefitCode" Type="PIA_BenefitMapping" />
    </Type>
  </Table>
  <Table Name="dbo.Benefits" Member="PiaMapping_AscensionBenefits">
    <Type Name="PiaMapping_AscensionBenefits">
      <Column Name="BenefitId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="BenefitCode" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="BenefitDescription" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="IsRxBenefit" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="IsMentalHealthBenefit" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="IsInpatientBenefit" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="IsOfficeVisitBenefit" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="IsEmergencyRoomBenefit" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Association Name="PiaMapping_AscensionBenefits_PIA_BenefitMapping" Member="PIA_BenefitMappings" ThisKey="BenefitId" OtherKey="AscensionBenefitId" Type="PIA_BenefitMapping" />
    </Type>
  </Table>
</Database>