<?xml version="1.0" encoding="utf-8"?>
<Database Name="David" Class="SchoolgroupAssignmentsDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=REN-SQL2;Initial Catalog=David;Integrated Security=True" SettingsObjectName="AscensionAnalytics.My.MySettings" SettingsPropertyName="DavidConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.SchoolgroupAssignments" Member="SchoolgroupAssignments">
    <Type Name="SchoolgroupAssignment">
      <Column Name="SchoolgroupAssignmentId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Schoolgroup_cd" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Column Name="SchoolgroupAssignmentTypeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AnalysisPersonId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="SchoolgroupAssignmentType_SchoolgroupAssignment" Member="SchoolgroupAssignmentType" ThisKey="SchoolgroupAssignmentTypeId" OtherKey="SchoolgroupAssignmentTypeId" Type="SchoolgroupAssignmentType" IsForeignKey="true" />
      <Association Name="SchoolgroupAssignmentSchoolgroup_SchoolgroupAssignment" Member="SchoolgroupAssignmentSchoolgroup" ThisKey="Schoolgroup_cd" OtherKey="schoolgroup_cd" Type="SchoolgroupAssignmentSchoolgroup" IsForeignKey="true" />
      <Association Name="AnalysisPeople_SchoolgroupAssignment" Member="AnalysisPeople" ThisKey="AnalysisPersonId" OtherKey="PersonId" Type="AnalysisPeople" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SchoolgroupAssignmentTypes" Member="SchoolgroupAssignmentTypes">
    <Type Name="SchoolgroupAssignmentType">
      <Column Name="SchoolgroupAssignmentTypeId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SchoolgroupAssignmentType" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="SchoolgroupAssignmentType_SchoolgroupAssignment" Member="SchoolgroupAssignments" ThisKey="SchoolgroupAssignmentTypeId" OtherKey="SchoolgroupAssignmentTypeId" Type="SchoolgroupAssignment" />
    </Type>
  </Table>
  <Table Name="dbo.schoolgroups" Member="SchoolgroupAssignmentSchoolgroups">
    <Type Name="SchoolgroupAssignmentSchoolgroup">
      <Column Name="prem_schoolid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="school_nm" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="prem_schoolgroupid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="claims_schoolgroupid" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="schoolgroup_cd" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Column Name="schoolgroup_nm" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="schoolgroup" Type="System.String" DbType="VarChar(63)" CanBeNull="true" />
      <Column Name="isConsortium" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Association Name="SchoolgroupAssignmentSchoolgroup_SchoolgroupAssignment" Member="SchoolgroupAssignments" ThisKey="schoolgroup_cd" OtherKey="Schoolgroup_cd" Type="SchoolgroupAssignment" />
    </Type>
  </Table>
  <Table Name="dbo.AnalysisPeople" Member="AnalysisPeoples">
    <Type Name="AnalysisPeople">
      <Column Name="PersonId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Phone" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Note" Type="System.String" DbType="VarChar(2000) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="IsActive" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Association Name="AnalysisPeople_SchoolgroupAssignment" Member="SchoolgroupAssignments" ThisKey="PersonId" OtherKey="AnalysisPersonId" Type="SchoolgroupAssignment" />
    </Type>
  </Table>
</Database>